/**
 * Created with IntelliJ IDEA.
 * User: jleo
 * Date: 13-1-7
 * Time: 下午10:07
 * To change this template use File | Settings | File Templates.
 */
class CompanyMapping {
    def static mapping = [:]

    static {
        mapping.put(11,"澳门");
        mapping.put(12,"立博");
        mapping.put(13,"永利高");
        mapping.put(14,"金宝博");
        mapping.put(15,"Crown");
        mapping.put(16,"12Bet");
        mapping.put(17,"易胜博");
        mapping.put(18,"Bet365");
        mapping.put(19,"伟德");
        mapping.put(20,"明升");
        mapping.put(21,"波音");
        mapping.put(22,"威廉希尔");
        mapping.put(23,"SSP");
        mapping.put(24,"Interwetten");
        mapping.put(25,"Oddset");
        mapping.put(26,"SNAI");
        mapping.put(27,"Eurobet");
        mapping.put(28,"博天堂");
        mapping.put(29,"互博国际");
        mapping.put(30,"香港马会");
        mapping.put(31,"新球");
        mapping.put(32,"乐天堂");
        mapping.put(33,"Derby");
        mapping.put(34,"环球沙巴");
        mapping.put(35,"10BET");
        mapping.put(36,"E乐博");
        mapping.put(37,"1Bet2Bet.com");
        mapping.put(38,"TitanBet");
        mapping.put(39,"利记");
        mapping.put(40,"发达");
        mapping.put(41,"IBCBET");
        mapping.put(50,"24hBET");
        mapping.put(51,"MeridianBet");
        mapping.put(52,"Miseojeu");
        mapping.put(53,"Misterbet");
        mapping.put(54,"8Dice");
        mapping.put(55,"Atlantik");
        mapping.put(56,"PartyBets");
        mapping.put(57,"Proline");
        mapping.put(58,"Singapore Pools");
        mapping.put(59,"BancoSport");
        mapping.put(60,"PinnacleSports");
        mapping.put(61,"必发");
        mapping.put(62,"Intralot");
        mapping.put(63,"优胜客");
        mapping.put(64,"24hPoker");
        mapping.put(65,"5 Dimes");
        mapping.put(66,"Admiral");
        mapping.put(67,"Astrabet");
        mapping.put(68,"Bet770");
        mapping.put(69,"Bwin");
        mapping.put(70,"BET1128");
        mapping.put(71,"Bet24");
        mapping.put(72,"Betako");
        mapping.put(73,"Astra Sport Bets");
        mapping.put(74,"Bet-at-home");
        mapping.put(75,"Bet7days");
        mapping.put(76,"BetClass");
        mapping.put(77,"BetClick");
        mapping.put(78,"BETCRIS");
        mapping.put(79,"BETDAQ");
        mapping.put(80,"BetAdria");
        mapping.put(81,"Jaxx");
        mapping.put(82,"Betfred");
        mapping.put(83,"Betaland");
        mapping.put(84,"Jennings");
        mapping.put(85,"Betboo");
        mapping.put(86,"Betoto");
        mapping.put(87,"BetChronicle");
        mapping.put(88,"Bets4all");
        mapping.put(89,"Betsafe");
        mapping.put(90,"BetClic.it");
        mapping.put(91,"Betshop");
        mapping.put(92,"betclick.fr");
        mapping.put(93,"Balkan Bet");
        mapping.put(94,"Betway");
        mapping.put(95,"Bet3000");
        mapping.put(96,"BINGOAL");
        mapping.put(97,"Blue Square");
        mapping.put(98,"BoDog");
        mapping.put(99,"Boylesports");
        mapping.put(100,"Canbet");
        mapping.put(101,"CaribSport");
        mapping.put(102,"Betfair.it");
        mapping.put(103,"Centrebet");
        mapping.put(104,"Chance");
        mapping.put(105,"Coral");
        mapping.put(106,"Betchoice");
        mapping.put(107,"BetPhoenix");
        mapping.put(108,"Tipsport-Sk");
        mapping.put(109,"Europlay");
        mapping.put(110,"Betplus");
        mapping.put(111,"Expekt");
        mapping.put(112,"BetGun.com");
        mapping.put(113,"Betliner");
        mapping.put(114,"BetTime");
        mapping.put(115,"Fortuna");
        mapping.put(116,"Betting2000");
        mapping.put(117,"Gamebookers");
        mapping.put(118,"Gamebookers Italia");
        mapping.put(119,"BetUK");
        mapping.put(120,"Globet");
        mapping.put(121,"GoldBet");
        mapping.put(122,"GWbet");
        mapping.put(123,"Hititbet");
        mapping.put(124,"IASbet.com");
        mapping.put(125,"Betpro.it");
        mapping.put(126,"Intertops");
        mapping.put(127,"LinesMaker");
        mapping.put(128,"Betsson Sportsbook");
        mapping.put(129,"Better.it");
        mapping.put(130,"Betshop.it");
        mapping.put(131,"Maxi-tip");
        mapping.put(132,"BetshopItalia");
        mapping.put(133,"MyBet.com");
        mapping.put(134,"NIKE");
        mapping.put(135,"Nordicbet");
        mapping.put(136,"Norway");
        mapping.put(137,"Odds4you");
        mapping.put(138,"Bookie Bob");
        mapping.put(139,"Paddy Power");
        mapping.put(140,"PAF");
        mapping.put(141,"Pianeta Scommesse");
        mapping.put(142,"BetUS");
        mapping.put(143,"Primebet");
        mapping.put(144,"C4A.com");
        mapping.put(145,"Redbet");
        mapping.put(146,"Completesportsbetting");
        mapping.put(147,"Sazka");
        mapping.put(148,"Derby-games.com");
        mapping.put(149,"ScommesseAndromeda");
        mapping.put(150,"Skybet");
        mapping.put(151,"SportBet");
        mapping.put(152,"Sportfanatik");
        mapping.put(153,"Bookmaker.com");
        mapping.put(154,"Digibet");
        mapping.put(155,"Sports.com");
        mapping.put(156,"Sportsbetting");
        mapping.put(157,"SPORTSinteraction");
        mapping.put(158,"SportsTAB");
        mapping.put(159,"Stan James");
        mapping.put(160,"StarPrice");
        mapping.put(161,"STS");
        mapping.put(162,"bwin.fr");
        mapping.put(163,"Dorobet");
        mapping.put(164,"Sweden");
        mapping.put(165,"Doxxbet");
        mapping.put(166,"Eurobet.it");
        mapping.put(167,"TipKurz");
        mapping.put(168,"Tipsport");
        mapping.put(169,"BWin.it");
        mapping.put(170,"Fubo.com");
        mapping.put(171,"Gioco digitale");
        mapping.put(172,"Tote");
        mapping.put(173,"Totesport");
        mapping.put(174,"TOTO");
        mapping.put(175,"TotoMix");
        mapping.put(176,"TotoSi");
        mapping.put(177,"Carib Sports");
        mapping.put(178,"TheBetArena");
        mapping.put(179,"CashPoint");
        mapping.put(180,"HappyBet");
        mapping.put(181,"Veikkaus");
        mapping.put(182,"Iceland");
        mapping.put(183,"CasinoSanremo.it");
        mapping.put(184,"Victory");
        mapping.put(185,"CBM Bookmaker");
        mapping.put(186,"VIP Sports");
        mapping.put(187,"wetten.de");
        mapping.put(188,"Wettpunkt");
        mapping.put(189,"Luxbet.com");
        mapping.put(190,"Cote Match");
        mapping.put(191,"Dansk Tipstjeneste");
        mapping.put(192,"WSEX");
        mapping.put(193,"Match Point");
        mapping.put(194,"Diamond Sportsbook");
        mapping.put(195,"e-stave");
        mapping.put(196,"sportsbook.com");
        mapping.put(197,"EurosportBET");
        mapping.put(198,"Tipico");
        mapping.put(199,"TopSport");
        mapping.put(200,"Vierklee");
        mapping.put(201,"Wagerweb");
        mapping.put(202,"WBX");
        mapping.put(203,"Wilson");
        mapping.put(204,"Win4real");
        mapping.put(205,"World-tip.com");
        mapping.put(206,"Jetbull");
        mapping.put(207,"eurosportbet.fr");
        mapping.put(208,"sportsbetting.com.au");
        mapping.put(209,"LEON");
        mapping.put(210,"Stryyke");
        mapping.put(211,"Evebet");
        mapping.put(212,"FiveBet");
        mapping.put(213,"Flemington Sportsbet");
        mapping.put(214,"Fonbet");
        mapping.put(215,"france-pari.fr");
        mapping.put(216,"Germania Sport");
        mapping.put(217,"Goalwin");
        mapping.put(218,"GoSportsbet");
        mapping.put(219,"Hrvatska Lutrija");
        mapping.put(220,"IA Sports");
        mapping.put(221,"iddaa");
        mapping.put(222,"ifortuna.eu");
        mapping.put(223,"Island Casino");
        mapping.put(224,"Islenskar Getraunir");
        mapping.put(225,"Kursaal Bookmaker");
        mapping.put(226,"Lavovi");
        mapping.put(227,"Legends");
        mapping.put(228,"Livebet");
        mapping.put(229,"Millebet.it");
        mapping.put(230,"Nike.sk");
        mapping.put(231,"Nine.com");
        mapping.put(232,"novibet");
        mapping.put(233,"Pamestihima");
        mapping.put(234,"Parier.net");
        mapping.put(235,"Parionsweb");
        mapping.put(236,"Players Only");
        mapping.put(237,"PMU");
        mapping.put(238,"power2bet");
        mapping.put(239,"SAjOO");
        mapping.put(240,"Samvo");
        mapping.put(241,"SBG Global");
        mapping.put(242,"Scandic Bookmakers");
        mapping.put(243,"Scommettendo");
        mapping.put(244,"Sportingbet.it");
        mapping.put(245,"Sports-1");
        mapping.put(246,"sportsalive.com");
        mapping.put(247,"Sportsbet");
        mapping.put(248,"Sportsbet.com.au");
        mapping.put(249,"sportsbetting.c");
        mapping.put(250,"Synot TIP");
        mapping.put(251,"SPORTSinteracti");
        mapping.put(252,"Stanleybet");
        mapping.put(253,"Startip");
        mapping.put(254,"Superbook");
        mapping.put(255,"SuperSport");
        mapping.put(256,"TAB Sportsbet");
        mapping.put(257,"TheGreek.com");
        mapping.put(258,"Tipos");
        mapping.put(259,"Tipsport.net");
        mapping.put(260,"Toals");
        mapping.put(261,"Tote betXpress");
        mapping.put(262,"Triobet");
        mapping.put(263,"Unibet.it");
        mapping.put(264,"Unitab");
        mapping.put(265,"World Sports Exchange");
        mapping.put(266,"Yabet");
        mapping.put(267,"youwin");
        mapping.put(268,"zedbet");
        mapping.put(269,"888Sport");
        mapping.put(270,"Bodog.com");
        mapping.put(271,"DiamondSportsBook");
        mapping.put(272,"Hollywood Sportsbook");
        mapping.put(273,"Jenningsbet");
        mapping.put(274,"myBet");
        mapping.put(275,"noxwin");
        mapping.put(276,"Offsidebet");
        mapping.put(277,"PariMatch");
        mapping.put(278,"Sportingbet AU");
        mapping.put(279,"Superbet.it");
        mapping.put(280,"32Red Bet");
    }
}
